---
title: "Theme_Category_Stats"
author: "JM Schneider"
date: "1/5/2021"
output: html_document
---

## Library Import
```{r,include=FALSE,echo=FALSE,warning=FALSE}
#Loading library
library(ez); library(ggplot2); library(multcomp); library(nlme); library(pastecs); library(reshape)
library(Hmisc); library (WRS2); library(lme4); library(lmerTest); library(plyr); library(splitstackshape) 
library(naniar); library(tidyr); library(dplyr); library(memisc); library(psychReport); library(foreign); library(interactions); library(tableone); library(officer); library(magrittr); library(corrplot); library(effectsize); library(Rcmdr)

julie.theme <- theme_bw() + theme(axis.line = element_line(colour = "black"), panel.grid.minor = element_blank(), panel.grid.major = element_blank(), panel.border = element_blank(), panel.background = element_blank(), legend.title= element_blank())  #custom graphics theme for ggplot2
```

## Import and clean data
```{r setup, include=FALSE}
setwd('/Users/julieschneider/Google Drive File Stream/My Drive/Manuscripts/manuscripts/semantic_processing/ERP')
df_new = read.csv('erp_stats.csv')
```

## Compute stats for ERP
```{r}
t.test(df_new$Unrelated_ERP, df_new$Related_ERP, paired =TRUE)
mean(df_new$Unrelated_ERP)
mean(df_new$Related_ERP)
t.test(df_new$Unrelated_ERSP, df_new$Related_ERSP, paired =TRUE)
```
## Correlation analysis
```{r}
cor.test(df_new$ERP_diff,df_new$ERSP_diff, method = c("pearson"))
cor.test(df_new$Related_ERP,df_new$Related_ERSP, method = c("pearson"))
cor.test(df_new$Unrelated_ERP,df_new$Unrelated_ERSP, method = c("pearson"))
```
### Plot Vocabulary regression
```{r}
#jpeg("correlation.jpeg")
ggplot(df_new, aes(x=ERP_diff, y = ERSP_diff)) + labs(title="Relationship between N400 & Theta", y = "Theta Amplitude", x = "N400 Amplitude") + geom_point(size=2,color='#E69F00') + julie.theme+ theme(plot.title = element_text(hjust = 0.5)) + geom_smooth(method=lm,  linetype="dashed",
             color="black")
#dev.off()
```

