---
title: "N400 + Theta in Preschoolers"
author: "JM Schneider"
date: "3/18/2021"
output: html_document
---

`## Library Import
```{r,include=FALSE,echo=FALSE,warning=FALSE}
#Loading library
library(ez); library(ggplot2); library(multcomp); library(nlme); library(pastecs); library(reshape)
library(Hmisc); library (WRS2); library(lme4); library(lmerTest); library(plyr); library(splitstackshape) 
library(naniar); library(tidyr); library(dplyr); library(memisc); library(psychReport); library(foreign); library(interactions); library(tableone); library(officer); library(magrittr); library(corrplot); library(effectsize); library(Rcmdr);library(scales)

julie.theme <- theme_bw() + theme(axis.line = element_line(colour = "black"), panel.grid.minor = element_blank(), panel.grid.major = element_blank(), panel.border = element_blank(), panel.background = element_blank(), legend.title= element_blank())  #custom graphics theme for ggplot2
```

## Import and merge data
```{r,include=FALSE,echo=FALSE,warning=FALSE}
df= read.csv("/Volumes/CallierResearch/Maguire/For RA use/Studies/Theme Category/Studies/JMS_N400_Theta/stats_output_031821_300-500.csv")
```

## Correlation
```{r}
cor<-cor.test(df$ERP_Diff, df$ERSP_Diff, method = c("pearson", "kendall", "spearman"))
cor$p.value
cor$estimate
cor$statistic
```

### Plot correlation
```{r}
#jpeg("Figs/vocab_regression_022321.jpeg")
ggplot(df, aes(x=ERP_Diff, y = ERSP_Diff)) + 
  labs(title="ERP & ERSP", y = "Theta Difference", x = "N400") + 
  geom_point(size=2,color='#E69F00') + 
  julie.theme+ 
  theme(plot.title = element_text(hjust = 0.5, size =20), axis.text = element_text(size = 20), axis.title = element_text(size=20)) +
  geom_smooth(method=lm,  linetype="dashed",
             color="black")
#dev.off()
```